<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <AssemblyName>ImproveGame</AssemblyName>
        <LangVersion>preview</LangVersion>
        <TargetFramework>net10.0</TargetFramework>
        <DebugMod> ; </DebugMod>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
        <PackageReference Include="FuzzySearch.Net" Version="1.1.0" />
        <!-- 夜幽模组构建工具 -->
        <PackageReference Include="Solaestas.tModLoader.ModBuilder" Version="1.6.1" />
        <!-- SilkyUI -->
        <ProjectReference Include="..\SilkyUIFramework\SilkyUIFramework.csproj" />
        <!-- SilkyUI 分析器 -->
        <ProjectReference Include="..\SilkyUIAnalyzer\SilkyUIAnalyzer.csproj">
            <OutputItemType>Analyzer</OutputItemType>
            <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
        </ProjectReference>
    </ItemGroup>

    <ItemGroup>
        <Reference Include="lib\*.dll" />
        <ModReference Include="lib\*.dll" />
    </ItemGroup>

    <ItemGroup>
        <AdditionalFiles Include="**/*.xml" Exclude="bin/**/*;obj/**/*" Pack="true" ModPath="%(Identity)" />

        <!-- 不在解决方案管理器显示 -->
        <None Visible="False" Include="./README.md;./README-en.md;./How-To-Use-Search.md" />
        <None Visible="False" Include="./icon.png;./icon_workshop.png" />
        <None Visible="False" Include="./changelog.txt;./description.txt;./description_workshop.txt;./description_workshop_en.txt" />
        <None Visible="False" Include="./.editorconfig;./.gitignore;./.gitattributes;././LICENSE" />
    </ItemGroup>
</Project>